### PR TITLE
Walkthrough

### PR DESCRIPTION
**Pull request by Jazmusic1234**
Finished adding walkthrough but may need to go back and adjust as changes are made to the website

### CODE REVIEW

**Comment by EthanWadsworth** [comment]
I took a look at it right now. I think it looks good, but just a couple of things I noticed. It might be worth having local storage save a user's timestamp as to when they last accessed the site. If they haven't used the site in the last 30 days for example, then we walk them through the tutorial again. Another thing to maybe add is a button to play the tutorial again if the user forgot how the application works. Other than that, looks good!

**Comment by Jazmusic1234** [comment]
I'll add the local storage feature as a new issue. 
I changed the help button so that it starts the walkthrough instead of opening the instructions panel since I figured the walkthrough essentially replaces it.

**Comment by dnthem** [comment]
I added localStorage so that if a user hasn't visited in 30 days, the tutorial will appear.

**Comment by dnthem** [comment]
Something you may consider: 
- Keep the help panel and add a button, like 'watch tutorial',  inside it

Bug:

- The side bar needs to expand in tutorial mode on small screen devices
image

**Pull request merged**
