### PR TITLE
changed timer inputs to number inputs with control logic

### PR DESCRIPTION
**Pull request by EthanWadsworth**

### CODE REVIEW

**Comment by dnthem** [comment]
https://user-images.githubusercontent.com/63533605/172244271-090f6771-f093-4aac-84c1-1da44986fc6d.mov

**Comment by EthanWadsworth** [comment]
I believe I fixed the default settings issue by moving the setDefaultSettings function into the timer.js file to have access to the variables that control the setting of the value of the timer beyond just the number inputs.

**Review by dnthem — APPROVED** [review]
Looks good

**Review by puzonevan — APPROVED** [review]
Nice! Just make sure it's tracked properly to develop and conflicts are merged when merging!

**Pull request merged**
