### PR TITLE
Skins/Themes #38

### PR DESCRIPTION
**Pull request by dnthem**
## Added Skins/Themes to the sidebar
- Three basic themes: Default, dark, light
- Color Blindness Mode
- Background Image: user can upload their own background

### Small changes in CSS:
- Adjusted some styling for sidebar container
- Removed borders

### Potential bugs/changes:
- Texts may become difficult to read in some backgrounds -> allow users to change the text color?
- ~~All default background images are from online sources (URLs) -> store as assets -> load time?~~
- ~~Background image does not fit the whole screen and gets repeated on large screen sizes.~~

## Update (06/05/2022): adjustments according to Baha's suggestions
Changes:
- When a theme is selected, it turns off color blind mode if it was on.
- Save custom background into local storage.

Fixes: 
- when turning on and then off color blind, it returns to the selected theme. Color blind does not work on image background.
- background image selection is now correctly selected when reloading.
- Set to default will get rid of the background image selection.

## Update (06/01/2022):
- Themes are now stored in localStorage, so user choices won't be lost when reloading the app

### CODE REVIEW

**Comment by EthanWadsworth** [comment]
Bug for the dark mode: It does not change the colors for any of the sidebar panels right now.

**Review by Jazmusic1234 — CHANGES_REQUESTED** [review]
Bugs:

- [x]  font color for the input task bar doesn't have enough contrast and is difficult to read in all themes
- [x] prev and next buttons for background music are hard to read in dark mode cause they are black
- [ ] add option for the user to remove the background after adding one

**Comment by dnthem** [comment]
@Jazmusic1234 for the last issue, the user can use the set to default button to remove background

**Comment by puzonevan** [comment]
@Jazmusic1234 for the last issue, the user can use the set to default button to remove background

**Review by Jazmusic1234 — APPROVED** [review]
One small thing is that on the dark theme, you may want to consider changing the color of the background music next and prev buttons when the user hovers over it to something lighter so that there's more contrast with the background. But other than that I think it looks great!
Screen Shot 2022-06-04 at 1 13 17 PM
Screen Shot 2022-06-04 at 1 13 35 PM

**Comment by keskinmbaha** [comment]
## Notes:
- If colorblind overrides a theme, then maybe colorblind should be a theme option or should clear the theme drop down
  - Same thing the other way around. You can override colorblind mode by choosing a theme, so either colorblind should be a theme or choosing a theme should turn the colorblind to off
- Maybe save the custom background into local storage as well
- Tutorial should also change themes

## Errors:
- Changing from color blind from on to off changes the theme back to default instead of the user selected theme.
- If you choose a background image and then reload the site, the background image is no longer selected in the settings even though it is being used
- Set to default should get rid of the background image selection in settings

**Comment by keskinmbaha** [comment]
Hey Evan and Tim good work, but I got another error:

1. Put in an image link and submit to change the background
2. Refresh the page
Now, none of the other default background options work and there is an error in the console.

Also, is the background image supposed to be cropped on smaller device screens?

https://user-images.githubusercontent.com/62824264/172097560-d5f78a0c-68b7-4623-88a6-3cb15a581154.mov

**Review by keskinmbaha — APPROVED** [review]

**Pull request merged**
